version: "3"

services:
  redis:
      image: 'redis:7.0.12-alpine'
      command: 'redis-server'
      ports:
        - "127.0.0.1:6379:6379"
  s3:
      image: localstack/localstack:latest
      ports:
        - "127.0.0.1:4566:4566"         
        - "127.0.0.1:4510-4559:4510-4559"
